### ISSUE TITLE
Imaging

### ISSUE THREAD

**Issue by Ganarajr** [AxisCommunications/discussions#77] opened 2022-10-05 04:14 UTC
### Discussed in https://github.com/orgs/AxisCommunications/discussions/76

<div type='discussions-op-text'>

<sup>Originally posted by **Ganarajr** October  5, 2022</sup>
Is there a way to configure Imaging paramters like ExposureValue using heapi calls similar to
//myserver/axis-cgi/param.cgi?action=list&group=Properties.PTZ.PTZ

More specifically are any cgis specific to Imaging apis available.</div>

**Comment by mattias-kindborg-at-work** [comment] 2022-10-05 15:22
Duplicate of #76

**Closed by mattias-kindborg-at-work** 2022-10-05 15:22 UTC
